### ISSUE TITLE
新規サーバでセットアップしたが実行できない

### ISSUE THREAD

**Issue by karasugawasu** [pooza/tomato-shrieker#643]
## 概要

新規サーバでtomato-shriekerのセットアップをしましたが、実行できませんでした
実行したセットアップ手順に不足ないでしょうか。
※急ぎではありませんので、確認出来るときにお願いいたします

## 現象

テストで失敗
```
Error: test_feed(TomatoShrieker::EntryTest): NoMethodError: undefined method `feed' for nil:NilClass
/home/karasugawa/tomato-shrieker/test/entry.rb:8:in `test_feed'
      5:     end
      6:
      7:     def test_feed
  =>  8:       assert_kind_of(FeedSource, @entries.sample.feed)
      9:     end
     10:
     11:     def test_template
```

bin/crawl.rbで失敗
```
/home/hogeuser/tomato-shrieker/app/lib/tomato_shrieker/source.rb:207:in `exec_all': undefined method `getopts' for []:Array (NoMethodError)
        from bin/crawl.rb:10:in `<main>'
```

## 期待される動作

テストをパスし、Crawlを実行できること

## 再現手順

1. rbenvで3.0.2のインストール
2. 一度も実行したことないサーバに新たにセットアップ（Wikiに従う）
3. テストの実行
4. bin/crawl.rbの実行

## 環境
CentOS 7.9
Ruby 3.0.2
tomato-shrieker 3.2.20

コンフィグ
```
sources:
  - source:
      url: https://github.com/weseek/growi/releases.atom
      negative_keyword: Merge pull request
    dest:
      template: title
      hooks:
        - https://md.korako.me/mulukhiya/webhook/xxxxxxxxxxxxxxxxxxxxxxx

slack:
  hooks:
    - https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxxxxx/slack
```
